### ISSUE TITLE
Insertion Error

### ISSUE THREAD

**Issue by deadcheat** [deadcheat/bloodpit#4]
```
breaking at exception: ArgumentError
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
Invalid argument: Instance of 'DateTime'
#0      StandardMessageCodec._writeValue (package:flutter/src/services/message_codecs.dart:344:7)
#1      StandardMessageCodec._writeValue (package:flutter/src/services/message_codecs.dart:334:9)
#2      StandardMessageCodec._writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:341:9)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#4      StandardMessageCodec._writeValue (package:flutter/src/services/message_codecs.dart:339:13)
#5      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:457:26)
#6      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:150:13)
<asynchronous suspension>
#7      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:28)
<asynchronous suspension>
#8      SqfliteDatabase.invokeMethod (package:sqflite/src/database.dart:1<…>

```

**Comment by deadcheat** [comment]
fixed
